### ISSUE TITLE
Create optimized meetup.com onebox

### ISSUE THREAD

**Issue by jqnatividad** [discourse/onebox#269]
The generic handling of meetup.com URLs (see #211) only shows the group name and its icon.  

![testing_onebox_support_-_lounge_-_talk_beta_nyc](https://cloud.githubusercontent.com/assets/1980690/5993182/31138662-aa15-11e4-9550-b220963a783b.jpg)

It doesn't show event specifics, which per iframely.com/debug, already creates all the required onebox info.

![embed_codes_for_meetup_-_iframely](https://cloud.githubusercontent.com/assets/1980690/5993178/151663e4-aa15-11e4-8957-011113245248.jpg)

**Comment by eviltrout** [comment]
I think iframely is doing a lot of extra work to build that view. I checked the URL for a meetup page and they don't have oembed, only open graph. So there's no clear iframe or something to embed to get that view.

**Comment by jqnatividad** [comment]
Meetup does have an oEmbed API though which doesn't require authentication (http://www.meetup.com/meetup_api/docs/oembed/), e.g.

https://api.meetup.com/oembed?&sign=true&photo-host=public&url=http://www.meetup.com/betanyc/events/219808865/

**Comment by iparamonau** [comment]
Hi guys, sorry to cut in. I am one of Iframely folks. We had this question from Discourse users before, so I figured it's time to address it. 

The issue here is that Onebox only handles oEmbeds via auto-discovery mechanism. People can white-list providers, yes. But in case of Meetup there's nothing to white-list. Whereas Iframely also has the list of "known" oEmbed publishers, and so discovers oEmbeds even without `<link rel application/oembed+json>` in the head. 

We saw the same problem in Discourse before with private/not published Vimeo videos. 

Here's the list of our current "discovery" regexps in case you would want to copy it:
https://github.com/itteco/iframely/blob/master/lib/plugins/system/oembed/providers.json



As a side question: 
how about implementing "oEmbed proxy" feature that can pass all URLs through single endpoint? It would right away support Iframely cloud API + open-source, Embedly etc. We have this approach in [Medium Insert Plugin](https://github.com/orthes/medium-editor-insert-plugin) that processes URLs through proxy endpoint, if configured. Otherwise, uses default handlers. We have [open api](http://oembedapi.com) for the use ad default config in open-source projects. 

Let me if you'd be interested in seeing more details in a separate ticket.

**Comment by jqnatividad** [comment]
Whoa! 1600!!! @iparamonau that's a long list of providers that will really juice up oneboxing if its implemented!  I'm more of a python/PHP guy, and would love to do a PR for this, but just don't have the skills nor the time. 
+100 for going thru the proxy! +10 on integrating regexps, if that can't be done.

**Comment by eviltrout** [comment]
@iparamonau that sounds very promising. Could you create that ticket? I would love to integrate that as long as it was an optional configuration thing.

Also thanks for the pointer to the discovery thing! I will have a look.
